FROM golang:1.14.15-alpine3.13 as debug

# installing git
RUN apk update && apk upgrade && \
    apk add --no-cache git \
        dpkg \
        gcc \
        git \
        musl-dev

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
ENV GO111MODULE on
RUN rm -rf /go/pkg/mod
RUN go get github.com/sirupsen/logrus@v1.3.0
RUN go get github.com/valyala/fasthttp@v1.0.0

# && go mod tidy && go get github.com/buaazp/fasthttprouter

RUN go get github.com/go-delve/delve/cmd/dlv@v1.1.0

WORKDIR /go/src/work
COPY ./src /go/src/work/

RUN go build -o app
### Run the Delve debugger ###
COPY ./dlv.sh /
RUN chmod +x /dlv.sh 
ENTRYPOINT [ "/dlv.sh"]

###########START NEW IMAGE###################

FROM alpine:3.9 as prod
COPY --from=debug /go/src/work/app /
CMD ./app
